CREATE DATABASE HELPDESK
USE HELPDESK

CREATE TABLE USERS (
    idUser INT PRIMARY KEY IDENTITY (1, 1),
    Pass VARCHAR (250) NOT NULL,
    Username VARCHAR (250) NOT NULL,
);

CREATE TABLE CLIENTES(
	idCliente INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR (100),
	Telefono VARCHAR (100)
);

CREATE TABLE TICKET(
	idTicket INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR (100),
	Fecha DATE,
	TipoTicket BIT,
	Status BIT,
	Descripcion VARCHAR (500),
	idCliente INT NOT NULL,
	idUser INT NOT NULL,
	FOREIGN KEY (idCliente) REFERENCES CLIENTES (idCliente),
	FOREIGN KEY (idUser) REFERENCES USERS (idUser)
);

CREATE TABLE REQUERIMIENTOS(
	idRequerimeinto INT PRIMARY KEY IDENTITY (1,1),
	Comentario VARCHAR (500),
	Fecha DATE,
	idTicket INT NOT NULL,
	FOREIGN KEY (idTicket) REFERENCES TICKET (idTicket)
	);